services:
  server:
    build: .
    env_file: .env
    volumes:
      - ./logs:/var/lib/server/logs

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    expose:
      - ${DB_PORT}:3306
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/import:/docker-entrypoint-initdb.d

  cache:
    image: redis:6.0-alpine
    volumes:
      - ./data/redis/:/data
    expose:
      - ${REDIS_PORT}:6379
    restart: unless-stopped
