name: Analytics Server

concurrency:
  group: analytics
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/analytics*'
  workflow_dispatch:

jobs:
  call_server_application_workflow:
    name: Server Application
    uses: standardnotes/server/.github/workflows/common-server-application.yml@main
    with:
      service_name: analytics
      workspace_name: "@standardnotes/analytics"
      deploy_web: false
      package_path: packages/analytics
    secrets: inherit

  newrelic:
    needs: call_server_application_workflow

    runs-on: ubuntu-latest

    steps:
      - name: Create New Relic deployment marker for Worker
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID_ANALYTICS_WORKER_PROD }}
          revision: "${{ github.sha }}"
          description: "Automated Deployment via Github Actions"
          user: "${{ github.actor }}"
