name: Api Gateway

concurrency:
  group: api_gateway
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/api-gateway*'
  workflow_dispatch:

jobs:
  call_server_application_workflow:
    name: Server Application
    uses: standardnotes/server/.github/workflows/common-server-application.yml@main
    with:
      service_name: api-gateway
      deploy_worker: false
      package_path: packages/api-gateway
    secrets: inherit

  newrelic:
    needs: call_server_application_workflow
    runs-on: ubuntu-latest
    steps:
      - name: Create New Relic deployment marker for Web
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID_API_GATEWAY_WEB_PROD }}
          revision: "${{ github.sha }}"
          description: "Automated Deployment via Github Actions"
          user: "${{ github.actor }}"
