name: Event Store

concurrency:
  group: event-store
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/event-store*'
  workflow_dispatch:

jobs:
  call_server_application_workflow:
    name: Server Application
    uses: standardnotes/server/.github/workflows/common-server-application.yml@main
    with:
      service_name: event-store
      workspace_name: "@standardnotes/event-store"
      e2e_tag_parameter_name: event_store_image_tag
      deploy_web: false
      package_path: packages/event-store
    secrets: inherit

  newrelic:
    needs: call_server_application_workflow

    runs-on: ubuntu-latest

    steps:
      - name: Create New Relic deployment marker for Worker
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID_EVENT_STORE_PROD }}
          revision: "${{ github.sha }}"
          description: "Automated Deployment via Github Actions"
          user: "${{ github.actor }}"
