name: Revisions Server

concurrency:
  group: revisions_server
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/revisions-server*'
  workflow_dispatch:

jobs:
  call_server_application_workflow:
    name: Server Application
    uses: standardnotes/server/.github/workflows/common-server-application.yml@main
    with:
      service_name: revisions
      workspace_name: "@standardnotes/revisions-server"
      e2e_tag_parameter_name: revisions_image_tag
      package_path: packages/revisions
    secrets: inherit

  newrelic:
    needs: call_server_application_workflow

    runs-on: ubuntu-latest
    steps:
      - name: Create New Relic deployment marker for Web
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID_REVISIONS_WEB_PROD }}
          revision: "${{ github.sha }}"
          description: "Automated Deployment via Github Actions"
          user: "${{ github.actor }}"
      - name: Create New Relic deployment marker for Worker
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID_REVISIONS_WORKER_PROD }}
          revision: "${{ github.sha }}"
          description: "Automated Deployment via Github Actions"
          user: "${{ github.actor }}"
