name: Websockets Server

concurrency:
  group: websockets
  cancel-in-progress: true

on:
  push:
    tags:
      - '*standardnotes/websockets-server*'
  workflow_dispatch:

jobs:
  call_server_utility_workflow:
    name: Server Utility
    uses: standardnotes/server/.github/workflows/common-server-utility.yml@main
    with:
      service_name: websockets
      workspace_name: "@standardnotes/websockets-server"
      package_path: packages/websockets
    secrets: inherit

  newrelic:
    needs: call_server_utility_workflow

    runs-on: ubuntu-latest
    steps:
      - name: Create New Relic deployment marker for Web
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID_WEBSOCKETS_WEB_PROD }}
          revision: "${{ github.sha }}"
          description: "Automated Deployment via Github Actions"
          user: "${{ github.actor }}"
      - name: Create New Relic deployment marker for Worker
        uses: newrelic/deployment-marker-action@v1
        with:
          accountId: ${{ secrets.NEW_RELIC_ACCOUNT_ID }}
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          applicationId: ${{ secrets.NEW_RELIC_APPLICATION_ID_WEBSOCKETS_WORKER_PROD }}
          revision: "${{ github.sha }}"
          description: "Automated Deployment via Github Actions"
          user: "${{ github.actor }}"
